# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 's'
    appType: 'webApp'
    WebAppName: 'calm-flower-5dbf22b9987a4a5a8a3a04cb7e806dc2'
    packageForLinux: '$(System.DefaultWorkingDirectory)/_Jinkouu_41026TuesGroup2/*''

# ignore the error with the name CopyFiles@2 and the targetFolder thing, it works
#- task: CopyFiles@2
#  inputs:
#    targetFolder: '$(Build.ArtifactStagingDirectory)'    
 
#- task: PublishBuildArtifacts@1    
#  displayName: 'Publish Artifact: drop'
#  inputs:
#    PathtoPublish: '$(build.artifactstagingdirectory)'